openapi: 3.0.1
info:
  title: DER Devices API
  description: Retrieve distributed energy resources data.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /der/devices:
    get:
      summary: Retrieve distributed energy resources data.
      operationId: get_der_devices
      tags:
        - system
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'deviceId': 'DER01', 'capacityKw': 75.5}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
