openapi: 3.0.1
info:
  title: SCADA Devices API
  description: Returns telemetry data from field SCADA devices.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /scada/devices:
    get:
      summary: Returns telemetry data from field SCADA devices.
      operationId: get_scada_devices
      tags:
        - system
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'deviceId': 'TX123', 'status': 'online', 'voltage': 12.8}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
