openapi: 3.0.1
info:
  title: Smart Meter Usage API
  description: Retrieves electricity usage data from smart meters.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /meters/{meterId}/usage:
    get:
      summary: Retrieves electricity usage data from smart meters.
      operationId: get_meters_{meterId}_usage
      tags:
        - system
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'meterId': 'MTR567', 'usageKWh': 34.2, 'timestamp': '2025-06-19T17:00:00Z'}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
