openapi: 3.0.1
info:
  title: Weather Forecast API
  description: Provides weather forecast for grid prediction.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /weather/forecast:
    get:
      summary: Provides weather forecast for grid prediction.
      operationId: get_weather_forecast
      tags:
        - system
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'region': 'Houston', 'temperature': 95, 'condition': 'Storm'}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
