openapi: 3.0.1
info:
  title: Agent-to-Agent Coordination API
  description: Enables coordination logic between mobile field agents and AI systems.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /a2a/coordination:
    post:
      summary: Enables coordination logic between mobile field agents and AI systems.
      operationId: post_a2a_coordination
      tags:
        - process
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'agentId': 'AGENT001', 'targetAgentId': 'AGENT005', 'task': 'power-restore', 'urgency': 'high'}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
