openapi: 3.0.1
info:
  title: Agent Priority Alerts API
  description: Retrieves time-sensitive alerts between agents for coordinated grid action.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /a2a/priority-alerts:
    get:
      summary: Retrieves time-sensitive alerts between agents for coordinated grid action.
      operationId: get_a2a_priority-alerts
      tags:
        - process
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'agentId': 'AGENT001', 'alerts': ['transformer overheating', 'crew reroute']}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
