openapi: 3.0.1
info:
  title: Critical Infrastructure Alert API
  description: Identifies outages affecting hospitals and emergency services.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /alerts/critical-infrastructure:
    get:
      summary: Identifies outages affecting hospitals and emergency services.
      operationId: get_alerts_critical-infrastructure
      tags:
        - process
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'facilityId': 'HOSP001', 'status': 'outage', 'priority': 'highest'}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
