openapi: 3.0.1
info:
  title: Crew Dispatch API
  description: Sends work order to field crews for deployment.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /dispatch/crew:
    post:
      summary: Sends work order to field crews for deployment.
      operationId: post_dispatch_crew
      tags:
        - process
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'crewId': 'CREW001', 'task': 'replace-transformer', 'location': 'Houston'}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
