openapi: 3.0.1
info:
  title: Grid Coordination API
  description: Coordinates grid restoration activities with agents.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /grid/coordination:
    post:
      summary: Coordinates grid restoration activities with agents.
      operationId: post_grid_coordination
      tags:
        - process
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'region': 'TX-78', 'outageEventId': 'EVT-001', 'priorityLevel': 'high'}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
