openapi: 3.0.1
info:
  title: Create Incident API
  description: Logs a grid outage or critical infrastructure failure.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /incident/create:
    post:
      summary: Logs a grid outage or critical infrastructure failure.
      operationId: post_incident_create
      tags:
        - process
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'region': 'TX-78', 'type': 'outage', 'priority': 'high'}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
