openapi: 3.0.1
info:
  title: MCP Grid Exchange API
  description: Coordinates decisions across grid operations through a central MCP control.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /mcp/grid-exchange:
    post:
      summary: Coordinates decisions across grid operations through a central MCP control.
      operationId: post_mcp_grid-exchange
      tags:
        - process
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'eventId': 'EVT-002', 'nodeId': 'GRID-009', 'action': 'reroute-load'}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
