openapi: 3.0.1
info:
  title: MCP Safety Orchestration API
  description: Triggers safety restoration flows via the Master Coordination Point.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /mcp/safety-orchestration:
    post:
      summary: Triggers safety restoration flows via the Master Coordination Point.
      operationId: post_mcp_safety-orchestration
      tags:
        - process
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'location': 'Clinic-A', 'trigger': 'life-support-priority', 'severity': 'critical'}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
