
rules:
  responses:
    errorResponses:
      - statusCode: 400
      - statusCode: 401
      - statusCode: 403
      - statusCode: 404
      - statusCode: 500
    payload:
      schema:
        type: object
        properties:
          code:
            type: string
          message:
            type: string
          timestamp:
            type: string
