openapi: 3.0.1
info:
  title: Agent Alerts API
  description: Provides targeted alerts to field agents.
  version: "1.0.0"
servers:
  - url: https://api.utility-ai.com/v1
paths:
  /agent/alerts:
    get:
      summary: Provides targeted alerts to field agents.
      operationId: get_agent_alerts
      tags:
        - experience
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example: {'agentId': 'AGENT001', 'alerts': ['restore', 'safety-check']}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  timestamp:
                    type: string
